CREATE table "EXAME_NF" (
    "IDNF"         NUMBER,
    "NUMERO"       NUMBER,
    "DATACADASTRO" DATE,
    "TOTALGERAL"   NUMBER,
    constraint  "EXAME_NF_PK" primary key ("IDNF")
)
/


CREATE TABLE "EXAME_ITEMNF" (
    "ITEMIDNF"  NUMBER,
    "IDNF"      NUMBER,
    "IDPRODUTO" NUMBER,
    "QTDE"      NUMBER,
    "VALOR"     NUMBER,
    CONSTRAINT "EXAME_ITEMNF_PK" PRIMARY KEY ("ITEMIDNF"),
    CONSTRAINT "EXAME_NF_FK" FOREIGN KEY ("IDNF") REFERENCES EXAME_NF("IDNF")
)